version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - DjangoBasic_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - djangobasic_static:/data/static/
      - djangobasic_media:/data/media/
      - djangobasic_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
      - djangobasic_log:/var/log/nginx/
    ports:
      - 7890:7890
    command: /var/log/nginx/django_access.log -o /var/log/nginx/report.html --log-format COMBINED --real-time-html

  django:
    image: djangobasic:v1.5.1
    networks:
      - DjangoBasic_network
    volumes:
      - djangobasic_static:/home/DjangoBasic/staticfiles/
      - djangobasic_media:/home/DjangoBasic/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - DjangoBasic_network
    volumes:
      - djangobasic_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  DjangoBasic_network:

volumes:
  djangobasic_static:
  djangobasic_media:
  djangobasic_mariadb:
  djangobasic_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true